HANDSHAKE_TIMEOUT = 2.0
READ_TIMEOUT_MIN  = 0.5
WRITE_TIMEOUT     = 1.0

MSG_ARDUINO_PRONTO = "ARDUINO_PRONTO"
MSG_PING           = "PING\n"
MSG_PONG           = "PONG"
MSG_DEBUG_ON       = "DEBUG_ON\n"
MSG_DEBUG_OFF      = "DEBUG_OFF\n"
